---
title: "Loop"
author: "ojasvi kumar"
date: "12/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

if else  loop 
```{r}
x<-readline(prompt = "Enter the value of x")
if(x<3){
 y<- 10
}else{
  y<- c(1:10)
}
y
```
for loop

```{r}
x<-c("a","b","c","d")
for (i in 1:4){
  print(x[i])
}
for (letter in x) {
  print(letter)
for (i in seq_along(x)) {
  print(x[i])
  
}
  
}
```
##seq_along() generates a sequence the same length of the argument passed, and in the context of a for loop is used to more easily generate the index to iterate over,
```{r}
x<-matrix(1:8,4,2,byrow = TRUE)
x
for (i in seq_len(nrow(x))) {
  for (j in seq_len(ncol(x))) {
    
  }
  
}
print(x[i,2])
```
```{r}
x <- 1:10
if(x > 5) {
        x <- 0
```


```{r}
f <- function(x) {
        g <- function(y) {
                y + z
        }
        z <- 4
        x + g(x)
}
```

```{r}
z<-5
```


```{r}
while (z>=3 && z<=10) {
  print(z)
  coin<- rbinom(1,1,0.5)
  if (coin==1){
    z<-z+1
  }else{
    z<-z-1
  }
}
```

```{r}
rbinom(1,1,0.5)
```
```{r}
for (i in 1:20){
  if(i<=10){
    next()
  }
  print("hello world")
}
```

